# fly.toml app configuration file generated for beth-twitter on 2023-09-21T20:49:12-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beth-twitter"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
